services:

  database:
    container_name: database
    image: mysql:8.0.33
    restart: always
    env_file:
      - .env  # Use the .env file for environment variables
    environment:
      MYSQL_DATABASE: workpermissiondatabase
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_PORT: 3307
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - workpermissionNetwork


  workpermission:
    image: 'workpermission:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workpermission
    restart: on-failure
    env_file:
      - .env  # Use the .env file for environment variables
    ports:
      - "2552:2552"
    environment:
      - server.port=2552
      - spring.datasource.username=${DATABASE_USERNAME}
      - spring.datasource.password=${DATABASE_PASSWORD}
      - WORK_PERMISSION_DB_IP=database
      - WORK_PERMISSION_DB_PORT=3307
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3307/workpermissiondatabase
    depends_on:
      - database
    networks:
      - workpermissionNetwork

networks:
  workpermissionNetwork: