server:
  port: 2552

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${WORK_PERMISSION_DB_IP:localhost}:${WORK_PERMISSION_DB_PORT:5432}/workpermissiondatabase
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:111111}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: workpermission

