server:
  port: 2552

# MYSQL
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    name: mysql
    url: jdbc:mysql://${WORK_PERMISSION_DB_IP:localhost}:${WORK_PERMISSION_DB_PORT:3306}/workpermissiondatabase
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  application:
    name: workpermission

# SWAGGER
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  override-with-generic-response: false

# Prometheus
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
  prometheus:
    metrics:
      export:
        enabled: true

